# Generated by Django 2.1.2 on 2019-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostchildinfo',
            name='content',
            field=models.CharField(max_length=400, verbose_name='部屋番号'),
        ),
    ]
